on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - elixir: 1.6
            otp: 20.3
          - elixir: 1.8.2
            otp: 21.3
          - elixir: 1.9.4
            otp: 22.2
          - elixir: 1.10.4
            otp: 23.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test --trace
